[package]
name = "osmo_crash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.5"
cosmwasm-schema = "1.5"
cw2 = "1.1"
cw-storage-plus = "1.2"
thiserror = "1"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
